name: mistr
favicon: null
layout_spectrum: 0.18296
typography_spectrum: 0.3872573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c33232'
    - '#ff0000'
    - '#aa0000'
    - '#7f0000'
    - '#aa5555'
  brandStrength: 0.75
  lightness: 0.9334122
  saturation: 0.3887042
  rhythmicContrast: 0.9439027
purpose: []
